# Workflow para build e deploy de um site Next.js estático no GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Roda quando pushes são feitos para a branch "main" (ou "master")
  push:
    branches: ["main", "master"]

  # Permite rodar este workflow manualmente pela aba Actions
  workflow_dispatch:

# Define permissões para o GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, cancelando execuções em progresso/pendentes
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install PNPM globally using NPM
        run: npm install -g pnpm@8 
        shell: bash

      - name: Install Dependencies with PNPM
        run: pnpm install --no-frozen-lockfile # <--- ALTERAÇÃO AQUI

      - name: Build with Next.js
        run: pnpm run build 

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out"

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
